import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Sanger Ramirez | Full Stack Engineer",
  description: "Explore Sanger Ramirez's portfolio impressive portfolio showcasing his skills and experience as a Full Stack Software Engineer",
  keywords: [
    "reactjs",
    "nextjs",
    "bootstrap",
    "responsivedesign",
    "seo",
    "ui/ux",
    "figma",
    "python",
    "nodejs",
    "expressjs",
    ".net",
    "fastapi",
    "restfulapis",
    "authentication",
    "access",
    "cmscustomization",
    "postgresql",
    "mysql",
    "sql",
    "git",
    "github",
    "ci/cd",
    "docker",
    "clouddeployment",
    "vercel",
    "aws",
    "jira",
    "googleanalytics",
    "versioncontrol",
    "performance",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Sanger Ramirez",
    url: "https://github.com/sangerramirez00",
  },
} as const;
